### ISSUE TITLE
convert keys in scan_appmanifest to lowercase

### ISSUE THREAD

**Issue by okletzmayr** [PYGU/patcher#8]
For some Steam installations the keys in the `appmanifest` files are not all lowercase, which leads to a crash if `appid` is formatted like `appID`.

```
Traceback (most recent call last):
  File "C:\Users\Oliver\Documents\GitHub\patcher\src\main.py", line 430, in <module>
  File "C:\Users\Oliver\Documents\GitHub\patcher\src\main.py", line 362, in scan_appmanifests
KeyError: 'appid'
Failed to execute script main
```

reported by @Legion495

**Comment by okletzmayr** [comment]
not wanting to reinvent the wheel myself, the application now imports [tivvit/python-case-insensitive-dict](https://github.com/tivvit/python-case-insensitive-dict).
